# Generated by Django 2.1.7 on 2019-05-24 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('generated_by_source_v1_id', models.CharField(blank=True, max_length=1024, null=True)),
                ('albums', models.ManyToManyField(blank=True, related_name='_album_albums_+', to='media.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('logs', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('content_hash', models.CharField(max_length=128)),
                ('origin_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('extract_path', models.CharField(max_length=1024)),
                ('transform_path', models.CharField(max_length=1024)),
                ('load_path', models.CharField(max_length=1024)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
                ('thumbnail_path', models.CharField(max_length=1024)),
                ('hidden', models.BooleanField(default=False)),
                ('byte_size', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('origin_path', models.CharField(max_length=1024)),
                ('content_path', models.CharField(max_length=1024)),
                ('discussion_path', models.CharField(max_length=1024)),
                ('legacy_order', models.IntegerField(blank=True, null=True)),
                ('legacy_v1_id', models.CharField(max_length=1024)),
                ('legacy_v2_id', models.CharField(max_length=1024)),
                ('sort_order', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SourceKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('path', models.CharField(max_length=1024)),
                ('mount_arguments', models.CharField(blank=True, max_length=1024, null=True)),
                ('unmount_arguments', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StorageKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('mount_script_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('unmount_script_path', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('album', models.ManyToManyField(to='media.Album')),
                ('media', models.ManyToManyField(to='media.Media')),
                ('sources', models.ManyToManyField(to='media.Source')),
            ],
        ),
        migrations.CreateModel(
            name='WebLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('url', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='storage',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.StorageKind'),
        ),
        migrations.AddField(
            model_name='source',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.SourceKind'),
        ),
        migrations.AddField(
            model_name='media',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.MediaKind'),
        ),
        migrations.AddField(
            model_name='media',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.Source'),
        ),
        migrations.AddField(
            model_name='job',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Media'),
        ),
        migrations.AddField(
            model_name='job',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='media.Source'),
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.JobStatus'),
        ),
        migrations.AddField(
            model_name='album',
            name='media',
            field=models.ManyToManyField(to='media.Media'),
        ),
        migrations.AddField(
            model_name='album',
            name='sources',
            field=models.ManyToManyField(to='media.Source'),
        ),
    ]
