# Generated by Django 2.1.7 on 2019-04-03 18:38

from django.db import migrations

def upsert_source_kinds(apps, schema_editor):
    kinds = [
        {
            'name': 'reddit',
            'description': 'A reddit account with saved posts to download.'
        },
        {
            'name': 'imgur',
            'description': 'An imgur album or direct image link to download.'
        },
        {
            'name': 'file-system',
            'description': 'A path to a local directory to import.'
        }
    ]

    SourceKind = apps.get_model('media', 'SourceKind')
    for kind in kinds:
        SourceKind.objects.update_or_create(
            name=kind['name'],
            description=kind['description']
        )

def upsert_storage_kinds(apps, schema_editor):
    kinds = [
        {
            'name': 'ecryptfs',
            'description': 'Encrypted file system requiring a password.',
            'mount_script_path': '<script>/ecryptfs/mount.sh',
            'unmount_script_path': '<script>/ecryptfs/unmount.sh'
        }
    ]

    StorageKind = apps.get_model('media', 'StorageKind')
    for kind in kinds:
        StorageKind.objects.update_or_create(
            name=kind['name'],
            description=kind['description'],
            mount_script_path=kind['mount_script_path'],
            unmount_script_path=kind['unmount_script_path']
        )

class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(upsert_source_kinds),
        migrations.RunPython(upsert_storage_kinds),
    ]
