# Generated by Django 2.1.7 on 2019-06-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_seed_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='meta_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
