# Generated by Django 2.1.7 on 2019-06-06 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_media_meta_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='meta_created',
            new_name='file_created',
        ),
    ]
