# Generated by Django 2.1.7 on 2019-04-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20190403_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
