# Generated by Django 2.1.7 on 2019-05-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_media_origin_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='byte_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
