# Generated by Django 2.1.7 on 2019-05-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_media_byte_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='media_id',
            new_name='media',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='source_id',
            new_name='source',
        ),
    ]
