# Generated by Django 2.1.7 on 2019-05-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_auto_20190520_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='order',
            new_name='sort_order',
        ),
    ]
