# Generated by Django 2.1.7 on 2019-05-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_auto_20190521_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='generated_by_source_v1_id',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
