# Generated by Django 2.1.7 on 2019-05-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_album_generated_by_source_v1_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
