# Generated by Django 2.1.7 on 2019-05-22 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0009_auto_20190522_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='kind_id',
            new_name='kind',
        ),
    ]
